tracing/syscalls: Rename variable 'nr' to 'syscall_nr'
There is a problem about duplicated variable name
for system call number and a argument of some
system call. I found this problem when I tested
perf-script with python script as below.

    # perf record -e syscalls:*
    # perf script -g python
    # perf script -s perf-script.py
      File "perf-script.py", line 8694
        def syscalls__sys_enter_io_getevents(event_name, context, common_cpu,
    SyntaxError: duplicate argument 'nr' in function definition
    Error running python script perf-script.py

As above, problems about duplicated argument occurred
when processing sys_enter_io_getevent() and sys_enter_io_submit().
Because the two system calls have a argument 'nr' as below.

    int io_getevents(aio_context_t ctx_id, long min_nr, long nr,
                     struct io_event *events, struct timespec *timeout);

    int io_submit(aio_context_t ctx_id, long nr, struct iocb **iocbpp);

So rename a variable 'nr' to 'syscall_nr' for system call number
in print_syscall_enter().

Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Lai Jiangshan <jiangshanlai@gmail.com>
Signed-off-by: Taeung Song <treeze.taeung@gmail.com>